FROM openjdk:11.0.10-jdk

EXPOSE 8080
WORKDIR /app

#add jar file
ADD target/demo-0.0.1-SNAPSHOT.jar /app/application.jar

#https://spring.io/guides/topicals/spring-boot-docker/
#指定容器启动程序及参数 <ENTRYPOINT> "<CMD>"
#ENTRYPOINT ["java","-jar","/app/application.jar","--dockerconfig=true"]
CMD java -jar /app/application.jar --server.port=8080