# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: Github Action Build Env
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [common]
# CI enviroment settings ${{ env.RELEASE_VERSION }} ${{ env.TAG_NAME }}
env:
  RELEASE_VERSION: "1.0" # version
jobs:
  build:
    name: Github Action Build
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    strategy:
      matrix:
        python-version: [ '3.9.7' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 #https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }} # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      #设置部分灵活的环境变量
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      
      #设置部分灵活的环境变量
      - name: Set environment variable with current time
        run: echo "BUILD_DATE=$(date)" >> $GITHUB_ENV
      
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"